# Generated by Django 3.2.7 on 2021-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.IntegerField(help_text='Year of Movie release', null=True, verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the movie', max_length=1000),
        ),
    ]
