# Generated by Django 3.2.7 on 2021-09-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210913_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinstance',
            old_name='book',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movieinstance',
            old_name='imprint',
            new_name='type',
        ),
    ]
