# Generated by Django 3.2.7 on 2021-09-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_movieinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(help_text='Add actor to this movie', to='catalog.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this movie', to='catalog.Genre'),
        ),
    ]
