# Generated by Django 3.2.7 on 2021-09-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210923_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient_card',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.doctor'),
        ),
    ]
