# Generated by Django 3.2.7 on 2021-09-29 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_auto_20210923_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_card',
            name='owner',
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='patient_card',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient_card',
            name='doctor',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
