# Generated by Django 3.2.7 on 2021-09-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210929_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.owner'),
        ),
    ]
