# Generated by Django 3.2.7 on 2021-10-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_animal_owner_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_card',
            name='doctor_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.doctor'),
        ),
    ]
