# Generated by Django 3.2.7 on 2021-10-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_patient_card_doctor_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
